### ISSUE TITLE
cannot open .sbf file

### ISSUE THREAD

**Issue by huachangmiao** [SilenceLeo/snowb-bmf#90] opened 2023-10-11 07:36 UTC
![image](https://github.com/SilenceLeo/snowb-bmf/assets/26161671/89a99245-daf6-4ea0-a3b0-3f3c4aeb724f)

**Comment by SilenceLeo** [comment] 2023-10-13 03:12
Duplicate of #89

**Closed by SilenceLeo** 2023-10-13 03:12 UTC
